### ISSUE TITLE
AttributeError: module 'torch.sparse' has no attribute 'torch'

### ISSUE THREAD

**Issue by jinserk** [gram-ai/capsule-networks#17]
I'm using pytorch `0.4.0a0+792daeb` and met the following attribute error:
```
Traceback (most recent call last):
  File "capsule_network.py", line 267, in <module>
    engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchnet-0.0.1-py3.6.egg/torchnet/engine/engine.py", line 39, in train
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torch/optim/adam.py", line 53, in step
    loss = closure()
  File "/home/jbaik/.pyenv/versions/3.6.4/lib/python3.6/site-packages/torchnet-0.0.1-py3.6.egg/torchnet/engine/engine.py", line 28, in closure
  File "capsule_network.py", line 190, in processor
    labels = torch.sparse.torch.eye(NUM_CLASSES).index_select(dim=0, index=labels)
AttributeError: module 'torch.sparse' has no attribute 'torch'
```
I guess the `torch.sparse.torch` might be removed recently, so what I have to do for a workaround?

**Comment by jinserk** [comment]
I replaced `torch.sparse.torch.eye` to `torch.eye` and it seems to work.
