### ISSUE TITLE
Training break at epoch 327 [ Reproducable] 

### ISSUE THREAD

**Issue by abduallahmohamed** [gram-ai/capsule-networks#4]
I trained the model couple of times, it always breaks are epoch 327, I'm using Nvidia GTX 1080 Ti. 

```

[Epoch 327] Testing Loss: 0.4562 (Accuracy: 99.52%)
Traceback (most recent call last):
  File "capsule_network.py", line 259, in <module>
    engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torchnet/engine/engine.py", line 22, in train
    self.hook('on_start_epoch', state)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torchnet/engine/engine.py", line 7, in hook
    self.hooks[name](state)
  File "capsule_network.py", line 218, in on_start_epoch
    state['iterator'] = tqdm(state['iterator'])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 783, in __init__
    total = len(iterable)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 880, in __len__
    else len(self.iterable) if hasattr(self.iterable, "__len__")
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 880, in __len__
    else len(self.iterable) if hasattr(self.iterable, "__len__")
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 880, in __len__
    else len(self.iterable) if hasattr(self.iterable, "__len__")
  [Previous line repeated 323 more times]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 304, in __len__
    return len(self.batch_sampler)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 127, in __len__
    return (len(self.sampler) + self.batch_size - 1) // self.batch_size
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 53, in __len__
    return len(self.data_source)
RecursionError: maximum recursion depth exceeded
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 891, in __del__
    self.close()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1102, in close
    if self.disable:
AttributeError: 'tqdm' object has no attribute 'disable'
```

**Comment by iwasaki-kenta** [comment]
Care to provide the checkpoint file for this epoch? I'll further debug it; it seems to be an issue with the data loader at that stage.

Many thanks for assisting in training it even further by the way.

**Comment by shivamberi** [comment]
We're you able to resolve the issue?

**Comment by abduallahmohamed** [comment]
Here it's: 
https://drive.google.com/file/d/14vP3SY67S4wA0naXBiIPb70lomO7SFR5/view?usp=sharing

**Comment by iwasaki-kenta** [comment]
Tried load the epoch in and it's training just fine. Really surprised about the accuracy hahah;

![image](https://user-images.githubusercontent.com/8392982/32670649-c8c67e24-c687-11e7-9e6d-0cdd479c5192.png)

Here's the code I used to load it.

```python
model = CapsuleNet()
model.load_state_dict(torch.load('epochs/epoch_327.pt'))
model.cuda()
```

**Comment by abduallahmohamed** [comment]
99.59% , is considered a saturation, maybe it needs to add a learning decay ? 

Also, this problem happens when you do training for 327 epochs 🍡

**Comment by iwasaki-kenta** [comment]
Care to provide the optimizer's `state_dict()` through `torch.save(...)` so that I may replicate the training process at epoch 327?

**Comment by abduallahmohamed** [comment]
I no longer have it , keep running it and it will happen.

**Comment by abduallahmohamed** [comment]
Also, I reproduced it twice.

**Comment by iwasaki-kenta** [comment]
I trained it until the 500th epoch and reached 99.7% validation accuracy. It's odd, I didn't get the error you had.

**Comment by abduallahmohamed** [comment]
I think it's something related to the python settings in my machine. 

Thanks !

**Comment by guerrillax** [comment]
same problem happend
[Epoch 327] Training Loss: 0.4538 (Accuracy: 99.98%)
[Epoch 327] Testing Loss: 0.4559 (Accuracy: 99.53%)
Traceback (most recent call last):
  File "capsule_network.py", line 263, in <module>
    
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchnet/engine/engine.py", line 22, in train
    self.hook('on_start_epoch', state)
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torchnet/engine/engine.py", line 7, in hook
    self.hooks[name](state)
  File "capsule_network.py", line 219, in on_start_epoch
    reset_meters()
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 783, in __init__
    total = len(iterable)
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 880, in __len__
    else len(self.iterable) if hasattr(self.iterable, "__len__")
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 880, in __len__
    else len(self.iterable) if hasattr(self.iterable, "__len__")
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 880, in __len__
    else len(self.iterable) if hasattr(self.iterable, "__len__")
  [Previous line repeated 323 more times]
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 304, in __len__
    return len(self.batch_sampler)
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 127, in __len__
    return (len(self.sampler) + self.batch_size - 1) // self.batch_size
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 53, in __len__
    return len(self.data_source)
RecursionError: maximum recursion depth exceeded
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 891, in __del__
    self.close()
  File "/home/zyang/anaconda2/envs/pytorch/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1102, in close
    if self.disable:
AttributeError: 'tqdm' object has no attribute 'disable'

**Comment by abduallahmohamed** [comment]
Because this bug is reproducible, I've created a pull request with fix for it. #12

**Comment by shariq-ali** [comment]
Dear i'm getting the following error. please help me i am new on this. 

[Epoch 1] Training Loss: 0.4539 (Accuracy: 99.98%)
Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f3e2cbc5a20>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e2cbc5a20>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/visdom/__init__.py", line 548, in _send
    data=json.dumps(msg),
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e2cbc5a20>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused


RecursionError                            Traceback (most recent call last)
<ipython-input-7-2e09d7936c4b> in <module>()
    279     engine.hooks['on_end_epoch'] = on_end_epoch
    280 
--> 281     engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)

5 frames
... last 2 frames repeated, from the frame below ...

/usr/local/lib/python3.6/dist-packages/torchnet/logger/visdomlogger.py in log(self, *args, **kwargs)
    158             # For some reason, the first point is a different trace. So for now
    159             # we can just add the point again, this time on the correct curve.
--> 160             self.log(*args, **kwargs)
    161 
    162 

RecursionError: maximum recursion depth exceeded while calling a Python object
