### ISSUE TITLE
Error during forward pass

### ISSUE THREAD

**Issue by NitinKumar94** [gram-ai/capsule-networks#8]
Hi! I get the following error stack trace when running the model. I have not made any changes to the code.

I would really appreciate any feedback! Thank you!

Traceback (most recent call last):
  File "capsule_network.py", line 264, in <module>
    engine.train(processor, get_iterator(True), maxepoch=NUM_EPOCHS, optimizer=optimizer)
  File "/home/ubuntu/anaconda3/envs/CapsuleNets/lib/python3.6/site-packages/torchnet/engine/engine.py", line 43, in train
    self.hook('on_end_epoch', state)
  File "/home/ubuntu/anaconda3/envs/CapsuleNets/lib/python3.6/site-packages/torchnet/engine/engine.py", line 7, in hook
    self.hooks[name](state)
  File "capsule_network.py", line 232, in on_end_epoch
    engine.test(processor, get_iterator(False))
  File "/home/ubuntu/anaconda3/envs/CapsuleNets/lib/python3.6/site-packages/torchnet/engine/engine.py", line 69, in test
    closure()
  File "/home/ubuntu/anaconda3/envs/CapsuleNets/lib/python3.6/site-packages/torchnet/engine/engine.py", line 61, in closure
    loss, output = state['network'](state['sample'])
  File "capsule_network.py", line 195, in processor
    classes, reconstructions = model(data)
  File "/home/ubuntu/anaconda3/envs/CapsuleNets/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "capsule_network.py", line 112, in forward
    y = Variable(torch.sparse.torch.eye(NUM_CLASSES)).cuda().index_select(dim=0, index=max_length_indices.data) 
RuntimeError: index_select(): argument 'index' must be Variable, not torch.cuda.LongTensor

**Comment by swordsmanxyz** [comment]
I add 'Variable()' outside the 'max_length_indices.data', and it works, but don't know if I do it right.

**Comment by NitinKumar94** [comment]
I got it working the same way. I think it should be right!
